const THEMES = {
  dark: {
    id: "dark",
    label: "Dark",
    base: "vs-dark",
    tokens: {
      "--bg-base": "#060a10",
      "--bg-primary": "#0b1018",
      "--bg-secondary": "#0f1620",
      "--bg-panel": "#111a26",
      "--bg-elevated": "#182230",
      "--bg-hover": "#1e2d40",
      "--bg-active": "rgba(56, 139, 253, 0.08)",
      "--bg-input": "#0d1520",
      "--bg-sidebar": "#0a1018",
      "--bg-activitybar": "#070c14",
      "--bg-statusbar": "#0a0e18",
      "--bg-tab-active": "#0f1620",
      "--bg-tab-inactive": "#0a1018",
      "--border-dim": "#12202e",
      "--border-default": "#1b2d42",
      "--border-bright": "#2a4a6a",
      "--border-active": "#388bfd",
      "--border-focus": "#58a6ff",
      "--text-primary": "#e2e8f0",
      "--text-secondary": "#94a3b8",
      "--text-muted": "#4a5568",
      "--text-dim": "#2d3748",
      "--text-link": "#58a6ff",
      "--accent-blue": "#60a5fa",
      "--accent-green": "#34d399",
      "--accent-amber": "#fbbf24",
      "--accent-red": "#f87171",
      "--accent-purple": "#a78bfa",
      "--accent-cyan": "#22d3ee",
      "--accent-orange": "#fb923c",
      "--accent-teal": "#2dd4bf",
      "--syntax-keyword": "#ff7b72",
      "--syntax-string": "#a5d6ff",
      "--syntax-number": "#79c0ff",
      "--syntax-comment": "#6a737d",
      "--syntax-function": "#d2a8ff",
      "--syntax-class": "#ffa657",
      "--syntax-operator": "#79c0ff",
      "--syntax-punctuation": "#8b949e",
      "--syntax-type": "#ffa657",
      "--syntax-variable": "#e2e8f0",
      "--syntax-constant": "#79c0ff",
      "--graph-node-fill": "#182230",
      "--graph-node-stroke": "#2a4a6a",
      "--graph-node-active": "#388bfd",
      "--graph-edge-stroke": "#2a4a6a",
      "--graph-label": "#94a3b8",
      "--graph-visited": "rgba(52, 211, 153, 0.25)",
      "--graph-queued": "rgba(251, 191, 36, 0.25)",
      "--graph-highlight": "rgba(96, 165, 250, 0.3)",
      "--scrollbar-track": "transparent",
      "--scrollbar-thumb": "#1b2d42",
      "--scrollbar-thumb-hover": "#2a4a6a",
      "--shadow-sm": "0 1px 3px rgba(0,0,0,0.4)",
      "--shadow-md": "0 4px 12px rgba(0,0,0,0.5)",
      "--shadow-lg": "0 12px 40px rgba(0,0,0,0.6)",
    },
  },
  light: {
    id: "light",
    label: "Light",
    base: "vs",
    tokens: {
      "--bg-base": "#ffffff",
      "--bg-primary": "#f8f9fb",
      "--bg-secondary": "#f0f2f5",
      "--bg-panel": "#f4f5f7",
      "--bg-elevated": "#ebedf0",
      "--bg-hover": "#e4e7eb",
      "--bg-active": "rgba(56, 139, 253, 0.08)",
      "--bg-input": "#ffffff",
      "--bg-sidebar": "#f4f5f7",
      "--bg-activitybar": "#ebedf0",
      "--bg-statusbar": "#f0f2f5",
      "--bg-tab-active": "#ffffff",
      "--bg-tab-inactive": "#f0f2f5",
      "--border-dim": "#e4e7eb",
      "--border-default": "#d1d5db",
      "--border-bright": "#9ca3af",
      "--border-active": "#2563eb",
      "--border-focus": "#3b82f6",
      "--text-primary": "#1e293b",
      "--text-secondary": "#475569",
      "--text-muted": "#94a3b8",
      "--text-dim": "#cbd5e1",
      "--text-link": "#2563eb",
      "--accent-blue": "#3b82f6",
      "--accent-green": "#10b981",
      "--accent-amber": "#d97706",
      "--accent-red": "#ef4444",
      "--accent-purple": "#8b5cf6",
      "--accent-cyan": "#06b6d4",
      "--accent-orange": "#ea580c",
      "--accent-teal": "#14b8a6",
      "--syntax-keyword": "#d73a49",
      "--syntax-string": "#032f62",
      "--syntax-number": "#005cc5",
      "--syntax-comment": "#6a737d",
      "--syntax-function": "#6f42c1",
      "--syntax-class": "#e36209",
      "--syntax-operator": "#005cc5",
      "--syntax-punctuation": "#24292e",
      "--syntax-type": "#e36209",
      "--syntax-variable": "#1e293b",
      "--syntax-constant": "#005cc5",
      "--graph-node-fill": "#f4f5f7",
      "--graph-node-stroke": "#d1d5db",
      "--graph-node-active": "#2563eb",
      "--graph-edge-stroke": "#9ca3af",
      "--graph-label": "#475569",
      "--graph-visited": "rgba(16, 185, 129, 0.2)",
      "--graph-queued": "rgba(217, 119, 6, 0.2)",
      "--graph-highlight": "rgba(59, 130, 246, 0.15)",
      "--scrollbar-track": "transparent",
      "--scrollbar-thumb": "#d1d5db",
      "--scrollbar-thumb-hover": "#9ca3af",
      "--shadow-sm": "0 1px 3px rgba(0,0,0,0.08)",
      "--shadow-md": "0 4px 12px rgba(0,0,0,0.1)",
      "--shadow-lg": "0 12px 40px rgba(0,0,0,0.15)",
    },
  },
  "high-contrast": {
    id: "high-contrast",
    label: "High Contrast",
    base: "hc-black",
    tokens: {
      "--bg-base": "#000000",
      "--bg-primary": "#000000",
      "--bg-secondary": "#0a0a0a",
      "--bg-panel": "#0a0a0a",
      "--bg-elevated": "#111111",
      "--bg-hover": "#1a1a1a",
      "--bg-active": "rgba(255, 255, 255, 0.06)",
      "--bg-input": "#000000",
      "--bg-sidebar": "#000000",
      "--bg-activitybar": "#000000",
      "--bg-statusbar": "#000000",
      "--bg-tab-active": "#0a0a0a",
      "--bg-tab-inactive": "#000000",
      "--border-dim": "#6fc3df",
      "--border-default": "#6fc3df",
      "--border-bright": "#ffffff",
      "--border-active": "#f38518",
      "--border-focus": "#f38518",
      "--text-primary": "#ffffff",
      "--text-secondary": "#d4d4d4",
      "--text-muted": "#a0a0a0",
      "--text-dim": "#666666",
      "--text-link": "#3794ff",
      "--accent-blue": "#6fc3df",
      "--accent-green": "#89d185",
      "--accent-amber": "#f38518",
      "--accent-red": "#f48771",
      "--accent-purple": "#b180d7",
      "--accent-cyan": "#6fc3df",
      "--accent-orange": "#f38518",
      "--accent-teal": "#89d185",
      "--syntax-keyword": "#569cd6",
      "--syntax-string": "#ce9178",
      "--syntax-number": "#b5cea8",
      "--syntax-comment": "#7ca668",
      "--syntax-function": "#dcdcaa",
      "--syntax-class": "#4ec9b0",
      "--syntax-operator": "#d4d4d4",
      "--syntax-punctuation": "#d4d4d4",
      "--syntax-type": "#4ec9b0",
      "--syntax-variable": "#ffffff",
      "--syntax-constant": "#4fc1ff",
      "--graph-node-fill": "#111111",
      "--graph-node-stroke": "#6fc3df",
      "--graph-node-active": "#f38518",
      "--graph-edge-stroke": "#6fc3df",
      "--graph-label": "#d4d4d4",
      "--graph-visited": "rgba(137, 209, 133, 0.35)",
      "--graph-queued": "rgba(243, 133, 24, 0.35)",
      "--graph-highlight": "rgba(111, 195, 223, 0.35)",
      "--scrollbar-track": "#000000",
      "--scrollbar-thumb": "#6fc3df",
      "--scrollbar-thumb-hover": "#ffffff",
      "--shadow-sm": "0 1px 3px rgba(255,255,255,0.05)",
      "--shadow-md": "0 4px 12px rgba(255,255,255,0.08)",
      "--shadow-lg": "0 12px 40px rgba(255,255,255,0.1)",
    },
  },
};

function themeToMonacoRules(themeConfig) {
  const t = themeConfig.tokens;
  return {
    base: themeConfig.base,
    inherit: true,
    rules: [
      {
        token: "",
        foreground: stripHash(t["--text-primary"]),
        background: stripHash(t["--bg-primary"]),
      },
      {
        token: "keyword",
        foreground: stripHash(t["--syntax-keyword"]),
        fontStyle: "bold",
      },
      {
        token: "keyword.control",
        foreground: stripHash(t["--syntax-keyword"]),
      },
      { token: "string", foreground: stripHash(t["--syntax-string"]) },
      { token: "string.key", foreground: stripHash(t["--syntax-string"]) },
      { token: "number", foreground: stripHash(t["--syntax-number"]) },
      {
        token: "comment",
        foreground: stripHash(t["--syntax-comment"]),
        fontStyle: "italic",
      },
      { token: "type", foreground: stripHash(t["--syntax-type"]) },
      { token: "type.identifier", foreground: stripHash(t["--syntax-class"]) },
      { token: "identifier", foreground: stripHash(t["--syntax-variable"]) },
      { token: "delimiter", foreground: stripHash(t["--syntax-punctuation"]) },
      {
        token: "delimiter.bracket",
        foreground: stripHash(t["--syntax-punctuation"]),
      },
      { token: "operator", foreground: stripHash(t["--syntax-operator"]) },
      { token: "annotation", foreground: stripHash(t["--syntax-function"]) },
      { token: "constant", foreground: stripHash(t["--syntax-constant"]) },
    ],
    colors: {
      "editor.background": t["--bg-primary"],
      "editor.foreground": t["--text-primary"],
      "editor.lineHighlightBackground": t["--bg-active"],
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground":
        themeConfig.id === "light" ? "#add6ff" : "#264f78",
      "editorCursor.foreground": t["--accent-cyan"],
      "editorLineNumber.foreground": t["--text-dim"],
      "editorLineNumber.activeForeground": t["--accent-amber"],
      "editorGutter.background": t["--bg-primary"],
      "editorWidget.background": t["--bg-panel"],
      "editorWidget.border": t["--border-default"],
      "editor.inactiveSelectionBackground": t["--bg-hover"],
      "editorIndentGuide.background": t["--border-dim"],
      "editorIndentGuide.activeBackground": t["--border-default"],
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": t["--scrollbar-thumb"] + "80",
      "scrollbarSlider.hoverBackground": t["--scrollbar-thumb-hover"],
      "scrollbarSlider.activeBackground": t["--scrollbar-thumb-hover"],
      "minimap.background": t["--bg-primary"],
    },
  };
}

function stripHash(color) {
  if (!color) return "e2e8f0";
  if (color.startsWith("#")) return color.slice(1);
  return color;
}

export { THEMES, themeToMonacoRules };
